[package]
name = "necklace-permutations"
version = "0.1.0"
edition = "2024"

[lib]
name = "necklace_permutations"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "np_benchmark"
harness = false