[package]
name = "xor_regression"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
ndarray = "0.16"
linfa = "0.8"
linfa-linear = "0.8"
rand = "0.9"
plotters = "0.3"
num-traits = "0.2"
