[package]
name = "simple-server"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
# See: https://github.com/time-rs/time/issues/693
time = ">= 0.3.38"