[package]
name = "plotters-3d-gallery"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinder_simd = { version = "0.5", features = ["pf-no-simd"] }
plotters = "0.3"
